(function(){
'use strict';
const C=ChartCore,L=ChartLayout,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={person:'<circle cx="12" cy="7" r="3.5"/><path d="M5 21v-3a7 7 0 0 1 14 0v3M9 15l3 3 3-3"/>',company:'<rect x="4" y="3" width="16" height="19" rx="2"/><path d="M8 7h1m6 0h1M8 11h1m6 0h1M8 15h1m6 0h1M10 22v-4h4v4"/>',organisation:'<path d="M3 9l9-6 9 6H3zm2 2v8m5-8v8m4-8v8m5-8v8M2 22h20M3 19h18"/>',account:'<rect x="2" y="5" width="20" height="15" rx="3"/><path d="M2 10h20M6 15h4m5 0h3"/>',location:'<path d="M19 10c0 5-7 12-7 12S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2.5"/>',object:'<path d="M3 7l9-5 9 5v11l-9 5-9-5V7zm0 0 9 5 9-5M12 12v11M7.5 4.5l9 5"/>',event:'<rect x="3" y="5" width="18" height="17" rx="2"/><path d="M3 10h18M7 2v6m10-6v6M7 14h3m4 0h3M7 18h3"/>',other:'<path d="M12 2l10 5v10l-10 5-10-5V7L12 2z"/><path d="M7 12h10m-5-5v10"/>',pin:'<path d="M8 2h8l-1 7 4 4H5l4-4-1-7zm4 11v9"/>'};
function icon(type,size=24){return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[type]||paths.other}</svg>`;}
let doc=C.empty(),geo=null,history=new C.History(),selected=new Set(),selection=null,view={x:0,y:0,k:1},busy=false,dirty=false,drag=null,frame=0,toastTimer;
const canvas=$('#canvas'),viewport=$('#viewport');
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function savePoint(){history.push(doc);dirty=true;}
function stats(){const p=L.projection(doc);$('#review-chart-button').hidden=!doc.graph.entities.length;$('#project-title').textContent=doc.title;$('#counts').textContent=`${doc.graph.entities.length} entities · ${doc.graph.relationships.length} links · ${doc.graph.groups.length} groups`;$('#entity-count').textContent=doc.graph.entities.length;$('#data-badge').textContent=doc.extraction?.reviewed?'Reviewed by you':doc.extraction?.kind==='reviewed'?'Reviewed sample':doc.extraction?.kind==='automatic'?'Review extraction':'Your chart';$('#scope').value=doc.visual.scope;$('#routing').value=doc.visual.routing;$('#scope-label').hidden=['flow','timeline'].includes(doc.layout.mode);$('#labels-button').setAttribute('aria-pressed',String(doc.visual.labels));$('#undo-button').disabled=!history.past.length;$('#redo-button').disabled=!history.future.length;$$('[data-mode]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.mode===doc.layout.mode)));const modeNames={relationship:doc.visual.scope==='key'?'Key links across the network':'The complete relationship network',flow:'Payments, benefits and contract awards',timeline:'Events in chronological order',hierarchy:'Directed relationships in layers',group:'Organisation groups and their members',mixed:'Grouped relationships with financial links highlighted'};$('#view-description').textContent=modeNames[doc.layout.mode]+` · ${p.nodes.length} visible`;$('#extraction-note').textContent=doc.extraction?.notice||(doc.graph.entities.length?'Imported graph. Click a node or link to edit its details.':'Text is processed offline. Review extracted relationships against your report.');const warnings=doc.extraction?.warnings||[];$('#review-summary').textContent=warnings.length?`${warnings.length} ${warnings.length===1?'passage needs':'passages need'} review`:'About extraction';$('#review-list').innerHTML=warnings.length?warnings.map(s=>`<p>${esc(s)}</p>`).join(''):'<p>Reported means stated in the source, not independently proven. The rule-based parser recognises a limited set of sentence patterns. Events may need splitting when a sentence mixes reported and suspected conduct.</p>';$('#add-node').disabled=doc.layout.mode==='timeline';$('#add-edge').disabled=doc.layout.mode==='timeline';$('#add-group').disabled=doc.layout.mode==='timeline';$('#empty-state h2').textContent=doc.graph.entities.length?'No entities in this view':'Turn your report into a chart';$('#empty-message').textContent=!doc.graph.entities.length?'Paste your report on the left, then choose Extract & review. Or load the reviewed example to explore.':doc.layout.mode==='timeline'?'This document has no dated events. Parse dated text or load JSON with events.':doc.visual.scope==='key'?'Choose All relationships to see entities without key links.':'Add an entity or parse your source text.';}
function pathFor(r){const p=r.points;if(!p.length)return '';if(r.curve&&p.length>2){let d=`M${p[0].x},${p[0].y}`;for(let i=1;i<p.length-1;i++){const prev=p[i-1],cur=p[i],next=p[i+1],a=Math.min(10,L.centre?Math.hypot(cur.x-prev.x,cur.y-prev.y)/3:10),b=Math.min(10,Math.hypot(next.x-cur.x,next.y-cur.y)/3);const da=Math.hypot(cur.x-prev.x,cur.y-prev.y)||1,db=Math.hypot(next.x-cur.x,next.y-cur.y)||1;d+=` L${cur.x-(cur.x-prev.x)/da*a},${cur.y-(cur.y-prev.y)/da*a} Q${cur.x},${cur.y} ${cur.x+(next.x-cur.x)/db*b},${cur.y+(next.y-cur.y)/db*b}`;}return d+` L${p.at(-1).x},${p.at(-1).y}`;}return p.map((q,i)=>`${i?'L':'M'}${q.x},${q.y}`).join(' ');}
function wrap(s,max=24,limit=2){const words=String(s).split(/\s+/),lines=[];let line='';for(const w of words){if((line+' '+w).trim().length>max&&line){lines.push(line);line=w;}else line+=(line?' ':'')+w;}if(line)lines.push(line);if(lines.length>limit){lines.length=limit;lines[limit-1]=lines[limit-1].slice(0,max-1)+'…';}return lines;}
function markerColour(r){if(['suspected','alleged','unverified'].includes(r.certainty))return 'amber';return C.moneyTypes.includes(r.type)&&r.type!=='contract'?'teal':r.type==='contract'?'blue':'grey';}
function render(recompute=true){
 if(recompute){ensurePositions();geo=L.geometry(doc,doc.layout.nodes);}if(!geo)return;stats();
 const masks=geo.routes.map((r,i)=>r.gaps?.length?`<mask id="line-break-${i}" maskUnits="userSpaceOnUse" x="${geo.bounds.x}" y="${geo.bounds.y}" width="${geo.bounds.width}" height="${geo.bounds.height}" style="mask-type:luminance"><rect x="${geo.bounds.x}" y="${geo.bounds.y}" width="${geo.bounds.width}" height="${geo.bounds.height}" fill="white"/>${r.gaps.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="${p.radius}" fill="black"/>`).join('')}</mask>`:'').join('');
 const defs=`<defs>${masks}<filter id="node-shadow" x="-10%" y="-20%" width="120%" height="150%"><feDropShadow dx="0" dy="2" stdDeviation="2" flood-color="#32527a" flood-opacity=".055"/></filter>${Object.entries({grey:'#91a0b5',teal:'#198c8c',blue:'#5279b6',amber:'#b58330',selected:'#245edb'}).map(([k,c])=>`<marker id="arrow-${k}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse" markerUnits="strokeWidth"><path d="M1 1 L9 5 L1 9" fill="none" stroke="${c}" stroke-width="1.5"/></marker>`).join('')}</defs>`;
 const groupHTML=geo.groups.map(g=>`<g class="graph-group ${selection?.kind==='group'&&selection.id===g.id?'selected':''}" data-group="${esc(g.id)}"><rect class="group-box" x="${g.x}" y="${g.y}" width="${g.width}" height="${g.height}"/><rect class="group-header-hit" x="${g.x}" y="${g.y}" width="${g.width}" height="43"/><text class="group-name" x="${g.x+16}" y="${g.y+25}">${esc(g.shortName||g.name.slice(0,24))}</text><text class="group-count" x="${g.x+60}" y="${g.y+25}">${esc(g.shortName?g.name.slice(0,Math.max(10,Math.floor((g.width-122)/6))):'')}</text><g class="collapse-control" data-collapse="${esc(g.id)}" role="button" tabindex="0" aria-label="Collapse ${esc(g.name)}"><rect x="${g.x+g.width-36}" y="${g.y+11}" width="22" height="22"/><text x="${g.x+g.width-25}" y="${g.y+28}">−</text></g></g>`).join('');
 const edgeHTML=geo.routes.map((r,i)=>{const chosen=selection?.kind==='edge'&&(selection.id===r.id||r.entries?.some(e=>e.id===selection.id));return `<g class="graph-edge" data-edge="${esc(r.id)}"><path class="edge-path ${esc(r.type)} ${esc(r.certainty)} ${chosen?'selected':''}" d="${pathFor(r)}" ${r.gaps?.length?`mask="url(#line-break-${i})"`: ''} ${r.directed?`marker-end="url(#arrow-${chosen?'selected':markerColour(r)})"`:''}/><path class="edge-hit" d="${pathFor(r)}"/><title>${esc([r.label,C.money(r),r.certainty,r.notes].filter(Boolean).join(' · '))}</title></g>`;}).join('');
 const labelHTML=geo.labels.map(l=>{const r=geo.routes.find(e=>e.id===l.edgeId),sel=selection?.kind==='edge'&&(selection.id===r.id||r.entries?.some(e=>e.id===selection.id));const shift=Math.hypot(l.x+l.width/2-l.anchor.x,l.y+l.height/2-l.anchor.y);const rows=l.rows||l.lines.map(text=>({text}));return `<g class="edge-label ${['suspected','alleged','unverified'].includes(r.certainty)?'uncertain':''} ${sel?'selected':''}" data-edge="${esc(r.id)}" role="button" tabindex="0" aria-label="${r.entries?'Inspect':'Edit'} ${esc(r.label)}">${shift>24?`<path class="label-leader" fill="none" d="M${l.anchor.x} ${l.anchor.y} L${l.x+l.width/2} ${l.y+l.height/2}"/>`:''}<rect x="${l.x}" y="${l.y}" width="${l.width}" height="${l.height}"/>${rows.map((row,i)=>`${row.kind==='entry-title'&&i?`<line class="transaction-divider" x1="${l.x+8}" x2="${l.x+l.width-8}" y1="${l.y+8+i*18}" y2="${l.y+8+i*18}"/>`:''}<text ${row.entryId?`data-edge="${esc(row.entryId)}"`:''} x="${l.x+l.width/2}" y="${l.y+18+i*18}" class="${row.kind==='amount'?'amount-line':''} ${['suspected','alleged','unverified'].includes(row.certainty)?'uncertain-entry':''}">${esc(row.text.length>(r.entries?44:34)?row.text.slice(0,r.entries?43:33)+'…':row.text)}${row.entryId?`<title>${esc(row.text)} — click to edit this transaction</title>`:''}</text>`).join('')}</g>`;}).join('');
 const nodeHTML=geo.nodes.map(n=>{const chosen=selected.has(n.id),org=['company','organisation'].includes(n.type),shortCode=org&&/^[A-Z]{2,8}\d*$/.test(n.id),name=shortCode&&!n.collapsed?n.id:n.name;const lines=wrap(name,n.type==='event'?28:17,n.type==='event'?3:2);const subtitle=n.collapsed?n.role:n.type==='person'?n.role:org?(shortCode&&n.name!==n.id?n.name:n.role||n.type):n.role;return `<g class="graph-node ${esc(n.type)} ${chosen?'selected':''}" transform="translate(${n.x},${n.y})" data-node="${esc(n.id)}" tabindex="0" role="button" aria-label="${esc(n.name)}. ${esc(n.role||n.type)}. ${doc.layout.nodes[n.id]?.pinned?'Pinned. ':''}Select to edit."><rect class="node-box" width="${n.width}" height="${n.height}"/><rect class="node-icon-bg" x="12" y="${n.type==='event'?15:(n.height-34)/2}" width="34" height="34"/><g class="node-icon" transform="translate(18,${n.type==='event'?21:(n.height-22)/2})">${icon(n.type,22)}</g>${lines.map((line,i)=>`<text class="node-name" x="57" y="${n.type==='event'?29+i*18:lines.length===2?24+i*16:29}">${esc(line)}</text>`).join('')}<text class="node-subtitle" x="57" y="${n.type==='event'?n.height-16:n.height-17}">${esc(String(subtitle||n.type).length>(n.type==='event'?36:21)?String(subtitle).slice(0,n.type==='event'?35:20)+'…':subtitle||n.type)}</text>${doc.layout.nodes[n.id]?.pinned?'<text class="pin-mark" x="175" y="14">◆</text>':''}${n.collapsed?'<text class="collapse-badge" x="175" y="14">+</text>':''}<title>${esc(n.name+'\n'+(n.role||''))}</title></g>`;}).join('');
 viewport.innerHTML=defs+groupHTML+edgeHTML+labelHTML+nodeHTML;applyView();$('#empty-state').hidden=geo.nodes.length>0;const m=geo.metrics;$('#quality-text').textContent=`${m.nodeOverlaps} node overlaps · ${m.crossings} crossings`;$('.quality-dot').style.background=(m.nodeOverlaps||m.edgeNodeHits||m.labelOverlaps)?'#b58330':'#18877d';renderEntityList();updateConnections();
}
function applyView(){viewport.setAttribute('transform',`translate(${view.x},${view.y}) scale(${view.k})`);$('#zoom-label').textContent=Math.round(view.k*100)+'%';}
function fit(){if(!geo?.nodes.length)return;const b=geo.bounds,w=canvas.clientWidth,h=canvas.clientHeight;view.k=Math.min(1.1,(w-60)/b.width,(h-100)/b.height);view.x=(w-b.width*view.k)/2-b.x*view.k;view.y=(h-b.height*view.k)/2-b.y*view.k+3;applyView();}
function focusNode(id){const n=geo.nodes.find(n=>n.id===id);if(!n)return;const c=L.centre(n);view.k=Math.max(view.k,.9);view.x=canvas.clientWidth/2-c.x*view.k;view.y=canvas.clientHeight/2-c.y*view.k;applyView();}
async function arrange(options={},record=true){if(busy)return;busy=true;$('#busy').hidden=false;$('#layout-button').disabled=true;$('#parse-button').disabled=true;$('#sample-button').disabled=true;$('#load-button').disabled=true;try{if(record)savePoint();await new Promise(r=>setTimeout(r,30));const result=await L.generate(doc,options);doc.layout.nodes=result.positions;doc.layout.lastCandidates=result.candidates;doc.layout.lastChosen=result.chosen;geo=result;render(false);if(!options.group)fit();if(record)toast(options.group?'Rearranged this group. Other entities kept their positions.':`Compared ${result.candidates.length} arrangements. Selected the clearest measured result.`);}catch(e){toast('Layout could not finish: '+e.message);console.error(e);}finally{busy=false;$('#busy').hidden=true;$('#layout-button').disabled=false;$('#parse-button').disabled=false;$('#sample-button').disabled=false;$('#load-button').disabled=false;}}
function freePosition(x,y){const boxes=Object.values(doc.layout.nodes).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));let p={x,y,width:L.W,height:L.H,pinned:false};for(let i=0;i<1500;i++){if(!boxes.some(b=>L.overlap(p,{width:L.W,height:L.H,...b},26)))return p;const a=i*2.4,r=40*Math.sqrt(i+1);p.x=x+Math.cos(a)*r;p.y=y+Math.sin(a)*r;}return p;}
function ensurePositions(){for(const n of L.projection(doc).nodes)if(!doc.layout.nodes[n.id])doc.layout.nodes[n.id]=freePosition((canvas.clientWidth/2-view.x)/view.k,(canvas.clientHeight/2-view.y)/view.k);}
function changed(){dirty=true;render();inspect();}
function select(kind,id,extend=false){if(kind==='node'){if(extend){if(selected.has(id))selected.delete(id);else selected.add(id);}else selected=new Set([id]);selection=selected.size===1?{kind,id:[...selected][0]}:selected.size?{kind:'multiple'}:null;}else{selected.clear();selection={kind,id};}render(false);inspect();}
function connectionContext(){
 if(!geo||doc.layout.mode==='timeline')return null;
 const id=selection?.kind==='node'?selection.id:selection?.kind==='group'?'@group:'+selection.id:null;
 if(!id||!geo.nodes.some(n=>n.id===id))return null;
 const routes=geo.routes.filter(r=>r.source===id||r.target===id),nodes=new Set([id,...routes.flatMap(r=>[r.source,r.target])]);
 return {id,routes,nodes,edges:new Set(routes.map(r=>r.id))};
}
function updateConnections(){
 const context=connectionContext();$('#connection-tools').hidden=!context;
 for(const el of $$('.graph-node')){el.classList.toggle('connection-muted',!!context&&!context.nodes.has(el.dataset.node));el.classList.toggle('connection-neighbour',!!context&&context.nodes.has(el.dataset.node)&&el.dataset.node!==context.id);}
 for(const el of $$('.graph-edge,.edge-label'))el.classList.toggle('connection-muted',!!context&&!context.edges.has(el.dataset.edge));
 if(context){const n=geo.nodes.find(n=>n.id===context.id);$('#connection-summary').textContent=`${n.name} · ${context.nodes.size-1} connected in this view`;}
}
function fitConnections(){
 const context=connectionContext();if(!context)return;
 const boxes=geo.nodes.filter(n=>context.nodes.has(n.id)).concat(geo.labels.filter(l=>context.edges.has(l.edgeId)),context.routes.flatMap(r=>r.points.map(p=>({...p,width:0,height:0}))));
 const b=L.extent(boxes),w=canvas.clientWidth,h=canvas.clientHeight;
 view.k=Math.min(1.4,(w-64)/Math.max(1,b.width),(h-110)/Math.max(1,b.height));view.k=Math.max(.08,view.k);
 view.x=w/2-(b.x+b.width/2)*view.k;view.y=h/2-(b.y+b.height/2)*view.k;applyView();
}
async function revealEntity(id){
 if(busy){toast('Wait for the current arrangement to finish.');return;}
 const n=doc.graph.entities.find(n=>n.id===id);if(!n)return;
 const hidden=!L.projection(doc).nodes.some(x=>x.id===id),switchMode=['timeline','flow'].includes(doc.layout.mode);
 if(hidden||switchMode){savePoint();if(switchMode)doc.layout.mode='relationship';if(doc.layout.mode==='group')doc.layout.groups[n.group]={...doc.layout.groups[n.group],expandedInGroupMode:true};else if(n.group)doc.layout.groups[n.group]={...doc.layout.groups[n.group],collapsed:false};if(!L.projection(doc).nodes.some(x=>x.id===id))doc.visual.scope='all';render();}
 closeSearch();select('node',id);focusNode(id);
}
let searchIndex=0;
function closeSearch(){$('#search-results').hidden=true;$('#chart-search').setAttribute('aria-expanded','false');$('#chart-search').removeAttribute('aria-activedescendant');}
function searchChart(){
 const input=$('#chart-search'),q=input.value.trim().toLowerCase();if(!q){closeSearch();return;}
 const matches=doc.graph.entities.filter(n=>`${n.name} ${n.id} ${n.role}`.toLowerCase().includes(q));
 $('#search-results').innerHTML=matches.length?matches.slice(0,12).map((n,i)=>`<button type="button" role="option" id="search-option-${i}" aria-selected="${i===0}" data-search-node="${esc(n.id)}"><strong>${esc(n.name)}</strong><small>${esc(n.role||n.type)}${n.name!==n.id?' · '+esc(n.id):''}</small></button>`).join('')+(matches.length>12?'<p>First 12 matches. Type more to narrow the list.</p>':''):'<p>No matches. Try another name or code.</p>';
 $('#search-results').hidden=false;input.setAttribute('aria-expanded','true');searchIndex=0;
 if(matches.length)input.setAttribute('aria-activedescendant','search-option-0');else input.removeAttribute('aria-activedescendant');
 $$('[data-search-node]').forEach(b=>b.onclick=()=>revealEntity(b.dataset.searchNode));
}
$('#chart-search').oninput=searchChart;$('#chart-search').onfocus=searchChart;
$('#chart-search').onkeydown=e=>{
 const options=$$('[data-search-node]');
 if(e.key==='Escape'){e.stopPropagation();closeSearch();return;}
 if($('#search-results').hidden)return;
 if(e.key==='Enter'){e.preventDefault();options[searchIndex]?.click();return;}
 if(['ArrowDown','ArrowUp'].includes(e.key)&&options.length){e.preventDefault();searchIndex=(searchIndex+(e.key==='ArrowDown'?1:-1)+options.length)%options.length;options.forEach((b,i)=>b.setAttribute('aria-selected',String(i===searchIndex)));$('#chart-search').setAttribute('aria-activedescendant',options[searchIndex].id);options[searchIndex].scrollIntoView({block:'nearest'});}
};
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.chart-search'))closeSearch();});
$('#fit-connections').onclick=fitConnections;
$('#clear-connections').onclick=()=>{selection=null;selected.clear();inspect();render(false);};
function preparePrint(){if(!geo?.nodes.length){$('#print-sheet').innerHTML='<p>Create a chart before printing.</p>';return;}$('#print-sheet').innerHTML=exportSVG();const svg=$('#print-sheet svg');
 // The hidden editor is still in the DOM during printing. Give this SVG its
 // own resources so arrows, crossing masks and shadows resolve inside it.
 const prefix=s=>s.replace(/url\(#([^)]+)\)/g,'url(#print-$1)');
 svg.querySelectorAll('[id]').forEach(el=>el.id='print-'+el.id);
 svg.querySelectorAll('*').forEach(el=>{for(const a of [...el.attributes])if(a.value.includes('url(#'))el.setAttribute(a.name,prefix(a.value));});
 svg.querySelectorAll('style').forEach(el=>el.textContent=prefix(el.textContent));
}
window.addEventListener('beforeprint',preparePrint);
window.addEventListener('afterprint',()=>{$('#print-sheet').innerHTML='';});
$('#print-button').onclick=()=>{if(!geo?.nodes.length){toast('Create a chart before printing.');return;}preparePrint();window.print();};
function field(label,name,value='',type='text'){return `<label class="field"><span>${esc(label)}</span><input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" step="any"':''}></label>`;}
function options(values,current){return values.map(v=>{const id=typeof v==='string'?v:v.id,label=typeof v==='string'?v:v.name;return `<option value="${esc(id)}" ${id===current?'selected':''}>${esc(label)}</option>`;}).join('');}
function selectField(label,name,values,current){return `<label class="field"><span>${esc(label)}</span><select name="${name}">${options(values,current)}</select></label>`;}
function textField(label,name,text){return `<label class="field"><span>${esc(label)}</span><textarea name="${name}">${esc(text||'')}</textarea></label>`;}
function sourceQuote(s){return `<div class="source-quote"><strong>Source wording</strong><p>${esc(s||'No source excerpt recorded. You can add notes to this item.')}</p></div>`;}
function inspect(){const pane=$('#inspector'),body=$('#inspector-content');pane.hidden=!selection;if(!selection)return;
 if(selection.kind==='multiple'){ $('#inspector-title').textContent='Selected entities';body.innerHTML=`<p>${selected.size} entities selected</p><div class="inspector-buttons"><button id="group-selection">Create group</button><button id="pin-selection">Pin selected</button><button id="unpin-selection">Unpin selected</button></div><p class="input-hint">Shift-click to add or remove entities from the selection.</p>`;$('#group-selection').onclick=addGroup;$('#pin-selection').onclick=()=>pinSelected(true);$('#unpin-selection').onclick=()=>pinSelected(false);return;}
 if(selection.kind==='node'&&selection.id.startsWith('@group:')){selection={kind:'group',id:selection.id.slice(7)};inspect();return;}
 if(selection.kind==='node'&&selection.id.startsWith('@event:')){const ev=doc.graph.events.find(e=>e.id===selection.id.slice(7));if(!ev)return;$('#inspector-title').textContent='Event details';body.innerHTML=`<form id="inspect-form">${textField('Event title','title',ev.title)}${field('Date (YYYY-MM or YYYY-MM-DD)','date',ev.date)}${selectField('Evidence status','certainty',C.certainty,ev.certainty)}<p class="input-hint">Participants: ${esc(ev.entities.join(', ')||'Not specified')}</p><button class="primary">Apply changes</button></form>${sourceQuote(ev.sourceText)}`;$('#inspect-form').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));savePoint();Object.assign(ev,v);changed();};return;}
 if(selection.kind==='group'){const g=doc.graph.groups.find(g=>g.id===selection.id);if(!g)return;const collapsed=doc.layout.mode==='group'?!doc.layout.groups[g.id]?.expandedInGroupMode:doc.layout.groups[g.id]?.collapsed;$('#inspector-title').textContent='Group details';body.innerHTML=`<form id="inspect-form">${field('Group name','name',g.name)}${field('Short label','shortName',g.shortName||'')}<p class="input-hint">${doc.graph.entities.filter(n=>n.group===g.id).length} entities in this group. Drag the heading to move them together.</p><div class="inspector-buttons"><button class="primary">Apply changes</button><button type="button" id="collapse-group">${collapsed?'Expand':'Collapse'}</button><button type="button" id="arrange-group">Arrange this group</button><button type="button" id="ungroup" class="danger">Ungroup</button></div></form>`;$('#inspect-form').onsubmit=e=>{e.preventDefault();savePoint();Object.assign(g,Object.fromEntries(new FormData(e.currentTarget)));changed();};$('#collapse-group').onclick=()=>collapse(g.id);$('#arrange-group').onclick=()=>{if(collapsed)collapse(g.id);arrange({group:g.id});};$('#ungroup').onclick=()=>confirmAction('Ungroup these entities?',`The ${doc.graph.entities.filter(n=>n.group===g.id).length} entities and all their links will remain.`,()=>{savePoint();doc.graph.entities.forEach(n=>{if(n.group===g.id)n.group='';});doc.graph.groups=doc.graph.groups.filter(x=>x.id!==g.id);selection=null;changed();});return;}
 if(selection.kind==='edge'){const bundle=geo.routes.find(e=>e.id===selection.id&&e.entries);if(bundle){$('#inspector-title').textContent='Transactions';body.innerHTML=`<div class="inspect-avatar"><span>${icon('account')}</span><div><strong>${bundle.entries.length} transactions</strong><small>${esc(bundle.entries[0].source)} → ${esc(bundle.entries[0].target)}</small></div></div><p class="input-hint">One shared line. Select an entry to edit its amount, date, status or other details.</p><div class="link-list">${bundle.entries.map(e=>`<button type="button" data-bundle-entry="${esc(e.id)}"><strong>${esc(e.label)}</strong><br><small>${esc([C.money(e),C.dateLabel(e.date),e.certainty].filter(Boolean).join(' · '))}</small></button>`).join('')}</div>`;$$('[data-bundle-entry]').forEach(b=>b.onclick=()=>select('edge',b.dataset.bundleEntry));return;}const r=doc.graph.relationships.find(e=>e.id===selection.id);if(!r){pane.hidden=true;return;}$('#inspector-title').textContent='Relationship details';body.innerHTML=`<form id="inspect-form">${selectField('From','source',doc.graph.entities,r.source)}${selectField('To','target',doc.graph.entities,r.target)}${field('Label','label',r.label)}${selectField('Type','type',['association','family','employment','ownership','meeting','communication','payment','benefit','contract','transaction'],r.type)}${selectField('Evidence status','certainty',C.certainty,r.certainty)}${field('Amount (HK$; leave blank if unknown)','amount',r.amount??'','number')}${field('Date (YYYY-MM or YYYY-MM-DD)','date',r.date||'')}${textField('Notes','notes',r.notes)}<label class="check-field"><input name="directed" type="checkbox" ${r.directed?'checked':''}> Show direction arrow</label><div class="inspector-buttons"><button class="primary">Apply changes</button><button type="button" class="danger" id="delete-item">Delete link</button></div></form>${sourceQuote(r.sourceText)}`;$('#inspect-form').onsubmit=e=>{e.preventDefault();const form=new FormData(e.currentTarget),v=Object.fromEntries(form);savePoint();Object.assign(r,v,{amount:v.amount===''?undefined:Number(v.amount),directed:form.has('directed'),currency:'HKD'});changed();toast('Relationship updated.');};$('#delete-item').onclick=()=>deleteSelection();return;}
 const n=doc.graph.entities.find(n=>n.id===selection.id);if(!n)return;$('#inspector-title').textContent='Entity details';body.innerHTML=`<div class="inspect-avatar"><span>${icon(n.type)}</span><div><strong>${esc(n.id)}</strong><small>${esc(n.type)}</small></div></div><form id="inspect-form">${field('Display name','name',n.name)}${selectField('Entity type','type',C.types,n.type)}${field('Role / description','role',n.role||'')}${selectField('Group','group',[{id:'',name:'No group'},...doc.graph.groups],n.group||'')}${textField('Notes','notes',n.notes)}<label class="check-field"><input name="pinned" type="checkbox" ${doc.layout.nodes[n.id]?.pinned?'checked':''}> Pin position during layout</label><div class="inspector-buttons"><button class="primary">Apply changes</button><button type="button" id="connect-item">Add link</button><button type="button" id="delete-item" class="danger">Delete entity</button></div></form><div class="link-list"><h3>Connected relationships</h3>${doc.graph.relationships.filter(r=>r.source===n.id||r.target===n.id).map(r=>`<button type="button" data-inspect-edge="${esc(r.id)}">${esc(r.label)}<br><small>${esc(r.source)} ${r.directed?'→':'—'} ${esc(r.target)} · ${esc(r.certainty)}</small></button>`).join('')||'<p class="input-hint">No links yet.</p>'}</div>`;
 $('#inspect-form').onsubmit=e=>{e.preventDefault();const form=new FormData(e.currentTarget),v=Object.fromEntries(form);savePoint();Object.assign(n,{name:v.name||n.id,type:v.type,role:v.role,group:v.group,notes:v.notes});if(doc.layout.nodes[n.id])doc.layout.nodes[n.id].pinned=form.has('pinned');changed();toast('Entity updated. Existing positions preserved.');};$('#delete-item').onclick=()=>deleteSelection();$('#connect-item').onclick=addEdge;$$('[data-inspect-edge]').forEach(b=>b.onclick=()=>select('edge',b.dataset.inspectEdge));
}
function pinSelected(value){savePoint();for(const id of selected)if(doc.layout.nodes[id])doc.layout.nodes[id].pinned=value;changed();}
let modalSubmit=null;
function showModal(title,body,submit,label='Save'){if($('#modal').open)$('#modal').close();$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;$('#modal-submit').textContent=label;$('#modal-submit').hidden=!submit;$('#modal-cancel').textContent=submit?'Cancel':'Close';modalSubmit=submit;$('#modal').showModal();}
$('#modal-form').onsubmit=e=>{e.preventDefault();if(modalSubmit){const result=modalSubmit(new FormData(e.currentTarget));if(result!==false)$('#modal').close();}};$('#modal-close').onclick=$('#modal-cancel').onclick=()=>$('#modal').close();
function confirmAction(title,message,callback){showModal(title,`<p>${esc(message)}</p>`,()=>callback(),'Confirm');}
const nextId=prefix=>{let i=1;while(doc.graph.entities.some(n=>n.id===prefix+i)||doc.graph.relationships.some(n=>n.id===prefix+i)||doc.graph.groups.some(n=>n.id===prefix+i))i++;return prefix+i;};
function addNode(){showModal('Add an entity',field('Name','name')+selectField('Type','type',C.types,'person')+selectField('Group','group',[{id:'',name:'No group'},...doc.graph.groups],''),form=>{const name=String(form.get('name')).trim();if(!name){toast('Enter a name.');return false;}savePoint();const id=nextId('entity-');doc.graph.entities.push({id,name,type:form.get('type'),group:form.get('group'),role:''});doc.layout.nodes[id]=freePosition((canvas.clientWidth/2-view.x)/view.k,(canvas.clientHeight/2-view.y)/view.k);doc.visual.revealed=[...(doc.visual.revealed||[]),id];render();select('node',id);toast('Entity added. Drag it into position.');},'Add entity');}
function addEdge(){if(doc.graph.entities.length<2){toast('Add at least two entities first.');return;}const current=selection?.kind==='node'&&!selection.id.startsWith('@')?selection.id:doc.graph.entities[0].id;showModal('Add a relationship',selectField('From','source',doc.graph.entities,current)+selectField('To','target',doc.graph.entities,doc.graph.entities.find(n=>n.id!==current)?.id)+field('Relationship label','label')+selectField('Type','type',['association','family','employment','ownership','meeting','communication','payment','benefit','contract','transaction'],'association')+selectField('Evidence status','certainty',C.certainty,'unverified')+field('Amount (HK$; optional)','amount','','number')+field('Date (optional)','date')+'<label class="check-field"><input name="directed" type="checkbox" checked> Show direction arrow</label>',form=>{if(!String(form.get('label')).trim()){toast('Enter a relationship label.');return false;}savePoint();const id=nextId('link-');doc.graph.relationships.push({id,...Object.fromEntries(form),directed:form.has('directed'),amount:form.get('amount')===''?undefined:Number(form.get('amount')),currency:'HKD'});doc.visual.revealedLinks=[...(doc.visual.revealedLinks||[]),id];render();select('edge',id);},'Add relationship');}
function addGroup(){const ids=[...selected].filter(id=>!id.startsWith('@'));showModal('Create a group',field('Group name','name')+`<p>${ids.length?`${ids.length} selected entities will join this group.`:'Create an empty group, then assign entities using the entity inspector.'}</p>`,form=>{const name=String(form.get('name')).trim();if(!name){toast('Enter a group name.');return false;}savePoint();const id=nextId('group-');doc.graph.groups.push({id,name});doc.graph.entities.filter(n=>ids.includes(n.id)).forEach(n=>n.group=id);selection={kind:'group',id};selected.clear();changed();},'Create group');}
function deleteSelection(){if(!selection)return;if(selection.kind==='edge'&&geo.routes.some(e=>e.id===selection.id&&e.entries)){toast('Select a transaction in the inspector to delete that entry.');inspect();return;}if(selection.kind==='node'){const id=selection.id;if(id.startsWith('@'))return;const related=doc.graph.relationships.filter(e=>e.source===id||e.target===id).length;confirmAction('Delete this entity?',`This will also remove ${related} connected links. You can undo this change.`,()=>{savePoint();doc.graph.entities=doc.graph.entities.filter(n=>n.id!==id);doc.graph.relationships=doc.graph.relationships.filter(e=>e.source!==id&&e.target!==id);doc.graph.events.forEach(e=>e.entities=e.entities.filter(x=>x!==id));delete doc.layout.nodes[id];selection=null;selected.clear();changed();});}else if(selection.kind==='edge'){const id=selection.id;confirmAction('Delete this relationship?','The entities will remain. You can undo this change.',()=>{savePoint();doc.graph.relationships=doc.graph.relationships.filter(r=>r.id!==id);selection=null;changed();});}}
function collapse(id){savePoint();const state=doc.layout.groups[id]||{};if(doc.layout.mode==='group')state.expandedInGroupMode=!state.expandedInGroupMode;else state.collapsed=!state.collapsed;doc.layout.groups[id]=state;if(doc.layout.mode==='group'?!state.expandedInGroupMode:state.collapsed){const members=doc.graph.entities.filter(n=>n.group===id).map(n=>({...n,...doc.layout.nodes[n.id]})).filter(n=>Number.isFinite(n.x));const b=L.extent(members);doc.layout.nodes['@group:'+id]={x:b.x,y:b.y,width:L.W,height:L.H,pinned:false};}selection={kind:'group',id};selected.clear();changed();}
function renderEntityList(){const q=$('#entity-search').value.trim().toLowerCase();$('#entity-list').innerHTML=doc.graph.entities.filter(n=>(n.name+' '+n.id+' '+n.role).toLowerCase().includes(q)).map(n=>`<button class="entity-list-row" data-find-node="${esc(n.id)}"><span class="entity-mini">${icon(n.type,17)}</span><span><strong>${esc(n.name)}</strong><small>${esc(n.role||n.type)}</small></span></button>`).join('');$$('[data-find-node]').forEach(b=>b.onclick=()=>revealEntity(b.dataset.findNode));}
async function replaceDocument(next){doc=C.validate(next);selected.clear();selection=null;history=new C.History();dirty=false;closeSearch();$('#chart-search').value='';$('#source-input').value=doc.graph.sources[0]?.text||'';inspect();const p=L.projection(doc);if(p.nodes.every(n=>doc.layout.nodes[n.id])){render();fit();}else await arrange({},false);}
function download(name,blob){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function filename(ext){return doc.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'.'+ext;}
function saveJSON(){download(filename('json'),new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}));dirty=false;toast('JSON saved with facts, positions and appearance.');}
function exportSVG(){const b=geo.bounds;const clone=viewport.cloneNode(true);clone.removeAttribute('transform');clone.querySelectorAll('.edge-hit,.group-header-hit,.collapse-control').forEach(el=>el.remove());clone.querySelectorAll('.selected,.connection-muted,.connection-neighbour').forEach(el=>el.classList.remove('selected','connection-muted','connection-neighbour'));const style=$('#app-style').textContent.split('/* SVG styles')[1]?.split('@media')[0]||'';return `<svg xmlns="http://www.w3.org/2000/svg" width="${Math.ceil(b.width)}" height="${Math.ceil(b.height+70)}" viewBox="${b.x} ${b.y-60} ${b.width} ${b.height+70}"><title>${esc(doc.title)}</title><desc>Reported means stated in source. Dashed amber links indicate suspected, alleged or unverified information. Green links show payments and benefits; blue links show contracts. Small breaks separate crossing lines; they do not indicate a connection.</desc><style>/* SVG styles${style}</style><rect x="${b.x}" y="${b.y-60}" width="${b.width}" height="${b.height+70}" fill="#f8fafe"/><text x="${b.x+22}" y="${b.y-29}" style="font:600 20px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;fill:#263c58">${esc(doc.title)}</text><text x="${b.x+22}" y="${b.y-8}" style="font:11px sans-serif;fill:#7b899b">${esc(doc.layout.mode)} view · Reported = stated in source · Dashed amber = uncertain</text>${clone.outerHTML}</svg>`;}
async function exportPNG(){const svg=exportSVG(),blob=new Blob([svg],{type:'image/svg+xml'}),url=URL.createObjectURL(blob);try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('Could not render the SVG export.'));img.src=url;});const scale=Math.min(2,8000/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.ceil(img.width*scale);c.height=Math.ceil(img.height*scale);const ctx=c.getContext('2d');ctx.scale(scale,scale);ctx.drawImage(img,0,0);const png=await new Promise(resolve=>c.toBlob(resolve,'image/png'));if(!png)throw Error('Image is too large to export.');download(filename('png'),png);toast('PNG exported.');}catch(e){toast(e.message);}finally{URL.revokeObjectURL(url);}}
function showExport(){showModal('Export the current view',`<p>Exports include the visible entities, relationship labels and evidence styles. Choose Save JSON to keep an editable copy.</p><div class="export-options"><button type="button" id="export-svg"><strong>SVG diagram</strong><small>Sharp at any size. Editable in vector design tools.</small></button><button type="button" id="export-png"><strong>PNG image</strong><small>A high-resolution image for reports and presentations.</small></button></div>`,null);$('#export-svg').onclick=()=>{download(filename('svg'),new Blob([exportSVG()],{type:'image/svg+xml'}));$('#modal').close();toast('SVG exported.');};$('#export-png').onclick=()=>{exportPNG();$('#modal').close();};}
function showMetrics(){const m=geo.metrics,cs=doc.layout.lastCandidates||[];showModal('Layout measurements',`<p>Crossings count intersecting or touching connector pairs before visual breaks. Small breaks keep unrelated lines visibly separate. Lower candidate cost is better; it is not a percentage of human satisfaction.</p><table class="metrics-table"><tbody>${[['Node overlaps',m.nodeOverlaps],['Edges through nodes',m.edgeNodeHits],['Label overlaps',m.labelOverlaps],['Edges through other labels',m.edgeLabelHits],['Crossings',m.crossings],['Bends',m.bends],['Group overlaps',m.groupOverlaps]].map(([n,v])=>`<tr><td>${n}</td><td>${v}</td></tr>`).join('')}</tbody></table><p>Last automatic arrangement: ${esc(doc.layout.lastChosen||'None')}. Manual edits change the measurements above.</p>${cs.length?`<table class="metrics-table"><thead><tr><th>Candidate</th><th>Crossings</th><th>Cost</th></tr></thead><tbody>${cs.map(c=>`<tr><td>${esc(c.name)}</td><td>${c.crossings}</td><td>${c.cost.toLocaleString()}</td></tr>`).join('')}</tbody></table>`:''}<p>Node collisions carry the highest penalty, followed by blocked edges, group overlaps and label collisions. The score also penalises crossings, bends, length and excessive canvas area.</p>`,null);}
async function applyReviewed(next,replacing){
 const valid=C.validate(next);
 if(replacing&&L.projection(valid).nodes.some(n=>!valid.layout.nodes[n.id])){
  busy=true;
  try{const result=await L.generate(valid);valid.layout.nodes=result.positions;valid.layout.lastCandidates=result.candidates;valid.layout.lastChosen=result.chosen;}
  finally{busy=false;}
 }
 // Commit only after validation and any new-report layout have succeeded.
 history.push(doc);doc=valid;dirty=true;selection=null;selected.clear();closeSearch();$('#chart-search').value='';
 $('#source-input').value=doc.graph.sources[0]?.text||'';inspect();render();if(replacing)fit();
 $('#review-details').open=!!doc.extraction?.warnings?.length;
 toast('Reviewed facts applied. Undo restores the previous chart.');
}
$('#parse-button').onclick=()=>{if(busy)return;try{const next=C.parse($('#source-input').value);ChartReview.open(next,{replacing:true,onApply:next=>applyReviewed(next,true)});}catch(e){toast(e.message);}};
$('#review-chart-button').onclick=()=>{if(busy)return;ChartReview.open(doc,{onApply:next=>applyReviewed(next,false)});};
$('#sample-button').onclick=()=>{if(dirty)confirmAction('Load the reviewed sample?','Unsaved changes will be replaced. Save JSON first if you want to keep them.',()=>replaceDocument(C.clone(Sample.document)));else replaceDocument(C.clone(Sample.document));};
$('#load-button').onclick=()=>$('#file-input').click();$('#file-input').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>8e6)throw Error('Choose a JSON file smaller than 8 MB.');const next=C.validate(JSON.parse(await file.text()));if(dirty)confirmAction('Open this chart?','Unsaved changes will be replaced. Save JSON first if needed.',()=>replaceDocument(next));else await replaceDocument(next);}catch(err){toast('Could not open JSON: '+err.message);}finally{e.target.value='';}};
$('#save-button').onclick=saveJSON;$('#export-button').onclick=showExport;$('#add-node').onclick=addNode;$('#add-edge').onclick=addEdge;$('#add-group').onclick=addGroup;$('#layout-button').onclick=()=>arrange();$('#fit-button').onclick=fit;$('#metrics-button').onclick=showMetrics;
$('#scope').onchange=async e=>{savePoint();doc.visual.scope=e.target.value;const p=L.projection(doc);if(p.nodes.some(n=>!doc.layout.nodes[n.id]))await arrange({},false);else{render();fit();}};
$('#routing').onchange=e=>{savePoint();doc.visual.routing=e.target.value;render();};$('#labels-button').onclick=()=>{savePoint();doc.visual.labels=!doc.visual.labels;render();};
$$('[data-mode]').forEach(b=>b.onclick=async()=>{if(busy||doc.layout.mode===b.dataset.mode)return;savePoint();doc.layout.mode=b.dataset.mode;if(['group','hierarchy','mixed'].includes(doc.layout.mode))doc.visual.scope='all';selection=null;selected.clear();inspect();await arrange({},false);});
function undo(){const old=history.undo(doc);if(!old)return;doc=old;selection=null;selected.clear();dirty=true;render();inspect();}function redo(){const next=history.redo(doc);if(!next)return;doc=next;selection=null;selected.clear();dirty=true;render();inspect();}
$('#undo-button').onclick=undo;$('#redo-button').onclick=redo;$('#close-inspector').onclick=()=>{selection=null;selected.clear();inspect();render(false);};
$('#source-toggle').onclick=()=>{const pane=$('#source-panel');pane.hidden=!pane.hidden;$('#source-toggle').setAttribute('aria-expanded',String(!pane.hidden));setTimeout(fit,10);};$('#source-tab').onclick=()=>{$('#source-content').hidden=false;$('#entities-content').hidden=true;$('#source-tab').classList.add('active');$('#entities-tab').classList.remove('active');};$('#entities-tab').onclick=()=>{$('#source-content').hidden=true;$('#entities-content').hidden=false;$('#source-tab').classList.remove('active');$('#entities-tab').classList.add('active');renderEntityList();};$('#entity-search').oninput=renderEntityList;
$('#project-title').ondblclick=()=>showModal('Rename chart',field('Chart title','title',doc.title),form=>{const title=String(form.get('title')).trim();if(!title)return false;savePoint();doc.title=title;stats();});
function zoom(factor,x=canvas.clientWidth/2,y=canvas.clientHeight/2){const k=Math.max(.08,Math.min(3,view.k*factor));view.x=x-(x-view.x)*k/view.k;view.y=y-(y-view.y)*k/view.k;view.k=k;applyView();}$('#zoom-in').onclick=()=>zoom(1.2);$('#zoom-out').onclick=()=>zoom(1/1.2);canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top);},{passive:false});
canvas.addEventListener('pointerdown',e=>{if(busy||e.button!==0)return;const collapseButton=e.target.closest('[data-collapse]');if(collapseButton){collapse(collapseButton.dataset.collapse);return;}const node=e.target.closest('[data-node]'),group=e.target.closest('[data-group]'),edge=e.target.closest('[data-edge]');if(edge){select('edge',edge.dataset.edge);return;}const origin={x:e.clientX,y:e.clientY};if(node){const id=node.dataset.node;if(!(selected.has(id)&&selected.size>1&&!e.shiftKey))select('node',id,e.shiftKey);if(e.shiftKey)return;let ids=[...selected];if(id.startsWith('@group:'))ids=[id,...doc.graph.entities.filter(n=>n.group===id.slice(7)).map(n=>n.id)];drag={kind:'nodes',origin,ids,positions:C.clone(doc.layout.nodes),moved:false};}else if(group){const id=group.dataset.group;select('group',id);drag={kind:'nodes',origin,ids:doc.graph.entities.filter(n=>n.group===id).map(n=>n.id),positions:C.clone(doc.layout.nodes),moved:false};}else{drag={kind:'pan',origin,view:{...view},moved:false};}canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.origin.x,dy=e.clientY-drag.origin.y;if(Math.abs(dx)+Math.abs(dy)>3&&!drag.moved){drag.moved=true;if(drag.kind==='nodes')savePoint();}if(!drag.moved)return;if(drag.kind==='pan'){view.x=drag.view.x+dx;view.y=drag.view.y+dy;applyView();}else{for(const id of drag.ids){const p=drag.positions[id];if(p)doc.layout.nodes[id]={...p,x:p.x+dx/view.k,y:p.y+dy/view.k};}if(!frame)frame=requestAnimationFrame(()=>{frame=0;render();});}});
function endDrag(){if(!drag)return;if(drag.kind==='pan'&&!drag.moved){selection=null;selected.clear();render(false);inspect();}else if(drag.moved&&drag.kind==='nodes'){render();inspect();}drag=null;}canvas.addEventListener('pointerup',endDrag);canvas.addEventListener('pointercancel',endDrag);
canvas.addEventListener('dblclick',e=>{const n=e.target.closest('[data-node]');if(n?.dataset.node.startsWith('@group:'))collapse(n.dataset.node.slice(7));else if(n){select('node',n.dataset.node);$('#inspector input')?.focus();}});
canvas.addEventListener('keydown',e=>{const c=e.target.closest('[data-collapse]'),n=e.target.closest('[data-node]'),r=e.target.closest('[data-edge]');if(e.key==='Enter'){e.preventDefault();if(c)collapse(c.dataset.collapse);else if(n)select('node',n.dataset.node);else if(r)select('edge',r.dataset.edge);}if(n&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const p=doc.layout.nodes[n.dataset.node];if(p){savePoint();p.x+=e.key==='ArrowLeft'?-10:e.key==='ArrowRight'?10:0;p.y+=e.key==='ArrowUp'?-10:e.key==='ArrowDown'?10:0;render();}}});
document.addEventListener('keydown',e=>{if($('#modal').open||ChartReview.isOpen)return;const typing=['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName);if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveJSON();return;}if(typing)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if(e.key==='f'||e.key==='F')fit();else if(e.key==='Escape'){selection=null;selected.clear();inspect();render(false);}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();deleteSelection();}});
$('#help-button').onclick=()=>showModal('Working with your chart',`<p><strong>Start with your report</strong><br>Paste text and choose Extract & review. Correct the draft, then choose Apply and draw. Use Review this chart to revisit the facts; applying corrections preserves positions and can be undone. The offline parser recognises explicit names, codes and supported relationship wording. Review the resulting facts and any passages listed under extraction notes. The reviewed example is available separately.</p><p><strong>Move and edit</strong><br>Drag an entity or a group heading. Click a link or entity for its inspector. Shift-click selects several entities for grouping. Pins protect positions during automatic layout.</p><p><strong>Choose a view</strong><br>Key links hides routine employment and peripheral details. All relationships shows the full graph. Money flow includes payments, benefits and contract awards; awards are not proof of payment. Timeline uses dated events.</p><p><strong>Read the chart</strong><br>Search by name or code. Select a person to highlight their visible direct connections. Fit connections zooms to those links; Clear restores the full view. No cards move.</p><p><strong>Print</strong><br>Print uses the whole current view, including its title and evidence legend, regardless of zoom. Choose paper size and orientation in the print dialogue.</p><p><strong>Keep your work</strong><br>Save JSON preserves facts and layout. SVG and PNG export the current view. Work is kept in memory until you save; there is no cloud or automatic disk save.</p><p><span class="help-key">⌘ / Ctrl Z</span> Undo &nbsp; <span class="help-key">⌘ / Ctrl S</span> Save &nbsp; <span class="help-key">F</span> Fit</p><p>Built with locally bundled ELK.js 0.10.0 (EPL-2.0). No external services are called.</p>`,null);
window.addEventListener('beforeunload',e=>{if(dirty||ChartReview.isOpen){e.preventDefault();e.returnValue='';}});window.addEventListener('resize',()=>{if(geo)fit();});
window.ChartApp={get document(){return doc;},get geometry(){return geo;},get selection(){return selection;},get busy(){return busy;},select,arrange,replaceDocument,exportSVG,exportPNG,undo,redo,collapse,fit,icon};
$('#source-panel').hidden=false;$('#source-toggle').setAttribute('aria-expanded','true');
$('#source-input').value='';stats();render();fit();
})();
