return await (async()=>{
const $=s=>document.querySelector(s),results=[];
const check=(ok,name)=>{results.push({name,pass:!!ok});if(!ok)throw Error(name);};
const idle=async()=>{const end=Date.now()+20000;while(ChartApp.busy){if(Date.now()>end)throw Error('Layout timed out');await new Promise(r=>setTimeout(r,30));}};
const edit=(sel,value)=>{const e=$(sel);e.value=value;e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));};
await idle();
const original=ChartCore.empty();original.title='Existing saved chart';original.graph.entities=[{id:'old',name:'Original person',type:'person'}];original.layout.nodes.old={x:100,y:140,width:190,height:68,pinned:true};
await ChartApp.replaceDocument(original);const before=JSON.stringify(ChartApp.document);
$('#source-input').value='In May 2024 David Wong paid HK$8,000 to Mary Chan, witnessed by Peter Lee. David Wong received money from Mary Chan.';
$('#parse-button').click();await idle();
check(JSON.stringify(ChartApp.document)===before,'parsing opens a draft without replacing the current chart');
check($('#review-dialog')?.open,'extracted facts open for review before drawing');
$('#review-cancel').click();check(JSON.stringify(ChartApp.document)===before&&!$('#review-dialog').open,'cancelling a draft leaves the chart unchanged');
$('#parse-button').click();
edit('[data-review-kind="entities"][data-review-id="David Wong"] [data-field="name"]','David Wong corrected');
$('#review-apply').click();await idle();
check(!$('#review-dialog').open,'applying valid review closes the dialogue');
check(ChartApp.document.graph.entities.find(n=>n.id==='David Wong').name==='David Wong corrected','review edits display name while retaining entity identity');
check(ChartApp.document.graph.relationships.some(e=>e.source==='David Wong'&&e.target==='Mary Chan'&&e.amount===8000),'review retains payment direction and amount');
check(ChartApp.document.graph.relationships.some(e=>e.source==='Mary Chan'&&e.amount===undefined),'unknown amount remains unknown');
const created=JSON.stringify(ChartApp.document);ChartApp.undo();check(JSON.stringify(ChartApp.document)===before,'undo restores the whole previous chart after applying a report');ChartApp.redo();check(JSON.stringify(ChartApp.document)===created,'redo restores the reviewed chart');
ChartApp.document.layout.nodes['David Wong'].pinned=true;
const positions=JSON.stringify(ChartApp.document.layout.nodes),facts=JSON.stringify(ChartApp.document.graph);
$('#review-chart-button').click();
edit('[data-review-kind="entities"][data-review-id="David Wong"] [data-field="name"]','Cancelled name');
$('#review-cancel').click();check(JSON.stringify(ChartApp.document.graph)===facts,'cancelling corrections does not mutate facts');
$('#review-chart-button').click();
edit('[data-review-kind="entities"][data-review-id="David Wong"] [data-field="name"]','Reviewed David');
$('#review-apply').click();await idle();
check(JSON.stringify(ChartApp.document.layout.nodes)===positions,'applying corrections preserves every existing coordinate and pin');
ChartApp.undo();check(JSON.stringify(ChartApp.document.graph)===facts,'review correction is one undoable change');
$('#review-chart-button').click();$('[data-review-tab="relationships"]').click();
const first=ChartApp.document.graph.relationships[0].id;
edit('[data-review-kind="relationships"][data-review-id="'+first+'"] [data-field="amount"]','-1');
$('#review-apply').click();check($('#review-dialog').open&&JSON.stringify(ChartApp.document.graph)===facts,'invalid amount cannot replace live facts');
edit('[data-review-kind="relationships"][data-review-id="'+first+'"] [data-field="amount"]','9000');
$('#review-apply').click();await idle();
check(ChartApp.document.graph.relationships[0].amount===9000,'corrected amount applies after validation');
ChartApp.undo();
$('#review-chart-button').click();$('[data-review-tab="entities"]').click();
const keep=$('[data-review-kind="entities"][data-review-id="Mary Chan"] [data-keep]');keep.click();
$('#review-apply').click();await idle();
check(!ChartApp.document.graph.entities.some(n=>n.id==='Mary Chan')&&!ChartApp.document.graph.relationships.some(e=>e.source==='Mary Chan'||e.target==='Mary Chan'),'excluding an entity leaves no dangling relationship');
check(ChartApp.document.graph.events.every(e=>!e.entities.includes('Mary Chan')),'excluded entity is removed from event participants');
ChartApp.undo();check(JSON.stringify(ChartApp.document.graph)===facts,'undo restores excluded facts and event participants');
const round=ChartCore.validate(JSON.parse(JSON.stringify(ChartApp.document)));check(JSON.stringify(round.graph)===facts,'reviewed facts survive JSON round trip');
$('#review-chart-button').click();$('[data-review-tab="passages"]').click();check($('#review-content').textContent.includes('witnessed by'),'unsupported witness wording remains available for review');$('#review-cancel').click();
const svg=ChartApp.exportSVG();check(!new DOMParser().parseFromString(svg,'image/svg+xml').querySelector('parsererror'),'reviewed chart exports valid SVG');
window.dispatchEvent(new Event('beforeprint'));check(!!$('#print-sheet svg'),'reviewed chart prepares a complete print image');window.dispatchEvent(new Event('afterprint'));
await ChartApp.replaceDocument(ChartCore.parse('Mr. Chan works for Blue Sky Engineering Ltd.'));
$('#review-chart-button').click();
edit('[data-review-kind="entities"][data-review-id="Blue Sky Engineering Ltd"] [data-field="name"]','Correct Company');
$('#review-apply').click();await idle();
check(ChartApp.document.graph.groups.find(g=>g.id==='Blue Sky Engineering Ltd').name==='Correct Company','correcting an organisation name updates its automatic group label');
check([...document.querySelectorAll('[data-node="Blue Sky Engineering Ltd"] .node-name')].map(n=>n.textContent).join(' ')==='Correct Company','corrected company name appears on the actual chart card');
$('#review-chart-button').click();$('#review-dialog').dispatchEvent(new Event('cancel',{cancelable:true}));
check(!$('#review-dialog').open,'Escape cancellation closes review without applying edits');
return results;
})()
